version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-proxy"
        versions: ">= 10.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.jarprocessor"
        versions: ">= 1.2.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.metadata.repository"
        versions: ">= 1.4.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.repository"
        versions: ">= 2.5.0"
      - dependency-name: "org.eclipse.platform:org.eclipse.equinox.p2.transport.ecf"
        versions: ">= 1.3.0"
  - package-ecosystem: "maven"
    directory: "/src/it/proxy-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/test1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/version-range"
    schedule:
      interval: "daily"
