version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/proxy-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/test1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/version-range"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
